task: 'wild'
subject: 'sample1_train'
experiment: 'direct_x4'

##############################################3
## Network Specs

# non-rigid motion mlp
non_rigid_motion_mlp:
  kick_in_iter: 100000
  full_band_iter: 200000

# pose decoder
pose_decoder:
  kick_in_iter: 20000

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'monocular_train'
  
train_romp_mask:
  dataset_module: 'core.data.human_nerf.train_romp_mask'
  dataset: 'monocular_train'

train_combo_mask:
  dataset_module: 'core.data.human_nerf.train_combo_mask'
  dataset: 'monocular_train'


progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'monocular_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'monocular_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'monocular_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'monocular_test'

4dview:
  dataset_module: 'core.data.human_nerf.4dview'
  dataset: 'monocular_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 1
